# Generated by Django 2.0 on 2019-05-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('experience', models.DecimalField(decimal_places=1, max_digits=3)),
                ('level', models.CharField(max_length=3)),
                ('salary', models.DecimalField(decimal_places=1, max_digits=10)),
                ('workinghour', models.DateTimeField()),
                ('dayoff', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cost', models.DecimalField(decimal_places=1, max_digits=4)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
